######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 25 13:09:39 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += connection.h selector.h text.h
SOURCES += connection.cpp fromegle.cpp text.cpp

QT += network
